- name: Sysctl settings | common-sysctl
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
  register: sysctl_config

- name: Apply sysctl if config changed | common-sysctl
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  command: sysctl -p
  when: sysctl_config.changed
