version: '3.3'

services:
  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - ingress
    deploy:
      labels:
        - traefik.frontend.rule=Host:{{ consul_fqdn }}
        - traefik.enable=false
        - traefik.port=8500
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-ingress}
        - traefik.docker.network=ingress_ingress
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users={{ basic_auth }}
  consul-replica:
    image: consul
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - ingress
    deploy:
      replicas: 0
      placement:
        preferences:
          - spread: node.id
  traefik:
    image: traefik:v1.7
    ports:
      - 81:81
      - 444:444
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:{{ traefik_fqdn }}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=ingress
        - traefik.docker.network=ingress_ingress
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users={{ basic_auth }}
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --constraints=tag==ingress
      --entrypoints='Name:http Address::81'
      --entrypoints='Name:https Address::444 TLS'
      --consul
      --consul.endpoint="consul-leader:8500"
      --acme
      --acme.email=dolan+bots@justdolanit.net
      --acme.storage="traefik/acme/account"
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onhostrule=true
      --acme.acmelogging=true
      --logLevel=INFO
      --accessLog
      --api
    networks:
      - ingress
    depends_on:
      - consul-leader

volumes:
  consul-data-leader:
  consul-data-replica:

networks:
  ingress:
