galaxy_info:
  author: "Golovanov Sergey <sg@fevlake.com>"
  description: "An [Ansible](https://www.ansible.com) role to setup [Dcoekr](https://www.docker.com/) infrastructure created for [Fevlake](https://fevlake.com) needs"
  license: MIT
  min_ansible_version: 2.6
  dependencies: []
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - stretch
        - jessie
  galaxy_tags:
    - ubuntu
    - debian
    - docker
